#!/bin/sh

DIRECTORY="$HOME/.local/state/startdwm"

if [ ! -d "$DIRECTORY" ]; then
    mkdir $DIRECTORY
fi

echo "content of this file is unrelevant. If this exists, dwm wont stop." > $DIRECTORY/lock

# The purpose of this script is to make dwm 'restartable' meaning that just closing dwm will
# restart it immediatly after, without closing the xsession, i.e. keeping every window open
while true
do
    xrandr --output DP-4 --rate 144 --mode 1920x1080 --primary
    xrandr --output HDMI-0 --rate 60 --mode 1920x1080 --left-of DP-4
    #dwm
    dwm 2> ~/.dwmlog
    if [ ! -f "$DIRECTORY/lock" ]; then
        break
    fi
    sleep 0.2
done
